spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 10