server:
    port: 8181
spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: postgres
        password: 31p6hd19
        driverClassName: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 10
    jooq:
        sql-dialect: postgres
#datasource:
#    driver: org.postgresql.Driver
#    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
#    username:
#    password:
