/*
 * This file is generated by jOOQ.
 */
package com.example.musicplatform.model.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetIndexes implements Serializable {

    private static final long serialVersionUID = 1L;

    private String indexName;

    public GetIndexes() {}

    public GetIndexes(GetIndexes value) {
        this.indexName = value.indexName;
    }

    public GetIndexes(
        String indexName
    ) {
        this.indexName = indexName;
    }

    /**
     * Getter for <code>public.get_indexes.index_name</code>.
     */
    public String getIndexName() {
        return this.indexName;
    }

    /**
     * Setter for <code>public.get_indexes.index_name</code>.
     */
    public GetIndexes setIndexName(String indexName) {
        this.indexName = indexName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GetIndexes other = (GetIndexes) obj;
        if (this.indexName == null) {
            if (other.indexName != null)
                return false;
        }
        else if (!this.indexName.equals(other.indexName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.indexName == null) ? 0 : this.indexName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GetIndexes (");

        sb.append(indexName);

        sb.append(")");
        return sb.toString();
    }
}
