/*
 * This file is generated by jOOQ.
 */
package com.example.musicplatform.model.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetUserLikedSongs implements Serializable {

    private static final long serialVersionUID = 1L;

    private String songTitle;
    private String artistName;

    public GetUserLikedSongs() {}

    public GetUserLikedSongs(GetUserLikedSongs value) {
        this.songTitle = value.songTitle;
        this.artistName = value.artistName;
    }

    public GetUserLikedSongs(
        String songTitle,
        String artistName
    ) {
        this.songTitle = songTitle;
        this.artistName = artistName;
    }

    /**
     * Getter for <code>public.get_user_liked_songs.song_title</code>.
     */
    public String getSongTitle() {
        return this.songTitle;
    }

    /**
     * Setter for <code>public.get_user_liked_songs.song_title</code>.
     */
    public GetUserLikedSongs setSongTitle(String songTitle) {
        this.songTitle = songTitle;
        return this;
    }

    /**
     * Getter for <code>public.get_user_liked_songs.artist_name</code>.
     */
    public String getArtistName() {
        return this.artistName;
    }

    /**
     * Setter for <code>public.get_user_liked_songs.artist_name</code>.
     */
    public GetUserLikedSongs setArtistName(String artistName) {
        this.artistName = artistName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GetUserLikedSongs other = (GetUserLikedSongs) obj;
        if (this.songTitle == null) {
            if (other.songTitle != null)
                return false;
        }
        else if (!this.songTitle.equals(other.songTitle))
            return false;
        if (this.artistName == null) {
            if (other.artistName != null)
                return false;
        }
        else if (!this.artistName.equals(other.artistName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.songTitle == null) ? 0 : this.songTitle.hashCode());
        result = prime * result + ((this.artistName == null) ? 0 : this.artistName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GetUserLikedSongs (");

        sb.append(songTitle);
        sb.append(", ").append(artistName);

        sb.append(")");
        return sb.toString();
    }
}
