/*
 * This file is generated by jOOQ.
 */
package com.example.musicplatform.model.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JwtToken implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID userId;
    private Boolean expired;
    private Boolean revoked;
    private String token;

    public JwtToken() {}

    public JwtToken(JwtToken value) {
        this.id = value.id;
        this.userId = value.userId;
        this.expired = value.expired;
        this.revoked = value.revoked;
        this.token = value.token;
    }

    public JwtToken(
        UUID id,
        UUID userId,
        Boolean expired,
        Boolean revoked,
        String token
    ) {
        this.id = id;
        this.userId = userId;
        this.expired = expired;
        this.revoked = revoked;
        this.token = token;
    }

    /**
     * Getter for <code>public.jwt_token.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.jwt_token.id</code>.
     */
    public JwtToken setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.jwt_token.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.jwt_token.user_id</code>.
     */
    public JwtToken setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.jwt_token.expired</code>.
     */
    public Boolean getExpired() {
        return this.expired;
    }

    /**
     * Setter for <code>public.jwt_token.expired</code>.
     */
    public JwtToken setExpired(Boolean expired) {
        this.expired = expired;
        return this;
    }

    /**
     * Getter for <code>public.jwt_token.revoked</code>.
     */
    public Boolean getRevoked() {
        return this.revoked;
    }

    /**
     * Setter for <code>public.jwt_token.revoked</code>.
     */
    public JwtToken setRevoked(Boolean revoked) {
        this.revoked = revoked;
        return this;
    }

    /**
     * Getter for <code>public.jwt_token.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>public.jwt_token.token</code>.
     */
    public JwtToken setToken(String token) {
        this.token = token;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JwtToken other = (JwtToken) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.expired == null) {
            if (other.expired != null)
                return false;
        }
        else if (!this.expired.equals(other.expired))
            return false;
        if (this.revoked == null) {
            if (other.revoked != null)
                return false;
        }
        else if (!this.revoked.equals(other.revoked))
            return false;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.expired == null) ? 0 : this.expired.hashCode());
        result = prime * result + ((this.revoked == null) ? 0 : this.revoked.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JwtToken (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(expired);
        sb.append(", ").append(revoked);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
