/*
 * This file is generated by jOOQ.
 */
package com.example.musicplatform.model.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Song implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID genreId;
    private String title;
    private LocalDateTime creationDate;
    private Integer likesCount;

    public Song() {}

    public Song(Song value) {
        this.id = value.id;
        this.genreId = value.genreId;
        this.title = value.title;
        this.creationDate = value.creationDate;
        this.likesCount = value.likesCount;
    }

    public Song(
        UUID id,
        UUID genreId,
        String title,
        LocalDateTime creationDate,
        Integer likesCount
    ) {
        this.id = id;
        this.genreId = genreId;
        this.title = title;
        this.creationDate = creationDate;
        this.likesCount = likesCount;
    }

    /**
     * Getter for <code>public.song.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.song.id</code>.
     */
    public Song setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.song.genre_id</code>.
     */
    public UUID getGenreId() {
        return this.genreId;
    }

    /**
     * Setter for <code>public.song.genre_id</code>.
     */
    public Song setGenreId(UUID genreId) {
        this.genreId = genreId;
        return this;
    }

    /**
     * Getter for <code>public.song.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.song.title</code>.
     */
    public Song setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>public.song.creation_date</code>.
     */
    public LocalDateTime getCreationDate() {
        return this.creationDate;
    }

    /**
     * Setter for <code>public.song.creation_date</code>.
     */
    public Song setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    /**
     * Getter for <code>public.song.likes_count</code>.
     */
    public Integer getLikesCount() {
        return this.likesCount;
    }

    /**
     * Setter for <code>public.song.likes_count</code>.
     */
    public Song setLikesCount(Integer likesCount) {
        this.likesCount = likesCount;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Song other = (Song) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.genreId == null) {
            if (other.genreId != null)
                return false;
        }
        else if (!this.genreId.equals(other.genreId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.creationDate == null) {
            if (other.creationDate != null)
                return false;
        }
        else if (!this.creationDate.equals(other.creationDate))
            return false;
        if (this.likesCount == null) {
            if (other.likesCount != null)
                return false;
        }
        else if (!this.likesCount.equals(other.likesCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.genreId == null) ? 0 : this.genreId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.creationDate == null) ? 0 : this.creationDate.hashCode());
        result = prime * result + ((this.likesCount == null) ? 0 : this.likesCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Song (");

        sb.append(id);
        sb.append(", ").append(genreId);
        sb.append(", ").append(title);
        sb.append(", ").append(creationDate);
        sb.append(", ").append(likesCount);

        sb.append(")");
        return sb.toString();
    }
}
