/*
 * This file is generated by jOOQ.
 */
package com.example.musicplatform.model.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFavouriteArtists implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID userId;
    private UUID artistId;

    public UserFavouriteArtists() {}

    public UserFavouriteArtists(UserFavouriteArtists value) {
        this.userId = value.userId;
        this.artistId = value.artistId;
    }

    public UserFavouriteArtists(
        UUID userId,
        UUID artistId
    ) {
        this.userId = userId;
        this.artistId = artistId;
    }

    /**
     * Getter for <code>public.user_favourite_artists.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.user_favourite_artists.user_id</code>.
     */
    public UserFavouriteArtists setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.user_favourite_artists.artist_id</code>.
     */
    public UUID getArtistId() {
        return this.artistId;
    }

    /**
     * Setter for <code>public.user_favourite_artists.artist_id</code>.
     */
    public UserFavouriteArtists setArtistId(UUID artistId) {
        this.artistId = artistId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserFavouriteArtists other = (UserFavouriteArtists) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.artistId == null) {
            if (other.artistId != null)
                return false;
        }
        else if (!this.artistId.equals(other.artistId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.artistId == null) ? 0 : this.artistId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserFavouriteArtists (");

        sb.append(userId);
        sb.append(", ").append(artistId);

        sb.append(")");
        return sb.toString();
    }
}
