openapi: 3.0.3
info:
  title: Common responses definitions
  description: Common responses definitions
  version: 1.0.0

paths: { }
components:
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          example: 'BadRequest'
        message:
          type: string
          example: Invalid request.
      required:
        - code
        - message
