/*
 * This file is generated by jOOQ.
 */
package com.example.musicplatform.model.enums;



import org.jooq.Catalog;
import org.jooq.EnumType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Role implements EnumType {

    admin("admin"),

    regular("regular"),

    artist("artist");

    private final String literal;

    private Role(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public String getName() {
        return "role";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Role lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Role.class, literal);
    }
}
